version: 2

updates:
  # Minor updates to production deps
  - package-ecosystem: "pip"
    ignore:
    - update-types:
        - version-update:semver-minor
        - version-update:semver-patch
    allow:
      - dependency-type: production
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    groups:
      pip-major-dependencies:
        dependency-type: "production"

  # Major updates to production deps
  - package-ecosystem: "pip"
    ignore:
    - update-types:
        - version-update:semver-major
    allow:
      - dependency-type: production
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    groups:
      pip-major-dependencies:
        dependency-type: "production"

      