version: 2

updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    groups:
      pip-major-dependencies:
        dependency-type: "production"
        update-types:
          - major
      pip-minor-dependencies:
        dependency-type: "production"
        update-types:
          - minor
          - patch
      pip-dev-dependencies:
        dependency-type: "development"