version: 2

updates:
  # Major updates to production deps
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      time: "12:15"
    groups:
      dependencies:
        dependency-type: production
        patterns:
        - "*"
        update-types:
        - "minor"
        - "patch"
      major-updates:
        dependency-type: production
        patterns:
        - "*"
        update-types:
        - "major"
    commit-message:
      include: scope
      prefix: build
        

      