version: 2

updates:
  # Major updates to production deps
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      time: "12:58"
    groups:
      pip-minor:
        dependency-type: production
        patterns:
        - "*"
        update-types:
        - "minor"
        - "patch"
      pip-major:
        dependency-type: production
        patterns:
        - "*"
        update-types:
        - "major"
      pip-dev:
        dependency-type: development
        patterns:
        - "*"
    commit-message:
      include: scope
      prefix: build
        

      